ISPP-12/SarandONGa

- requirements.txt
Added mysqlclient module for project-database connection.
> FIX(#1): UPDATE REQUIREMENTS FILE

- .github/workflows/main.yml
- README.md
- SarandONGa/settings.py
- requirements.txt
Added the main workflow of the project.
Check if it complies with the established:
> FEAT(#16): CONFIGURE GITHUB ACTIONS 

- .gitignore
- SarandONGa/settings.py
- stock/admin.py
- stock/apps.py
- stock/models.py
- stock/tests.py
- stock/views.py
Creation of stock app and model in order to achieve core use case management.
> FEAT(#4): CREATION OF STOCK MODEL

- SarandONGa/urls.py
- main/templates/subsidy_form.html
- subsidy/forms.py
- subsidy/models.py
- subsidy/views.py
Create form for subsidies. Str method fixed in Subsidy model and verbose names added in attributes so they display in Spanish.
> FEAT(#55): CREATE FORM FOR SUBSIDIES

- SarandONGa/settings.py
- person/admin.py
- person/models.py
I have additionally modified the Person model and the admin.py file so that there are no errors.
> CREATE GODFATHER MODEL

- person/admin.py
- person/models.py
The model is defined inside the Person app, and added to the Django admin panel.
Check if it complies with the established:
> FEAT(#105): CREATE THE ASEM USER MODEL

- .gitignore
- SarandONGa/settings.py
- beneficiary/admin.py
- beneficiary/apps.py
- beneficiary/models.py
- beneficiary/tests.py
- beneficiary/views.py
Creation of Beneficiary app and model ir order to achieve core use case management of beneficiaries:
Creation of a beneficiary app
Creation of a beneficiary model
Beneficiary model connected with admin panel
> FEAT(#23): CREATION OF BENEFICIARY MODEL

- SarandONGa/urls.py
- main/templates/subsidy_list.html
- subsidy/views.py
Creation of a list for the subsidy object showing all subsidies.
> FEAT(#119): CREATION OF SUBSIDY LIST

- person/models.py
The type of user and the method of sending correspondence have been added.
> FEAT(#105): ADD ATTRIBUTES TO THE ASEM USER MODEL

- SarandONGa/urls.py
- main/templates/asem_user/asem_user_form.html
- person/forms.py
- person/models.py
- person/views.py
Create function and form for ASEM users.
> FEAT(#106): CREATION AND FORM FOR ASEM USERS

- main/templates/components/select.html
- main/templates/index.html
- main/views.py
- static/styles/master.css
Created select + label component in order to use it in form views. To check it out just access to: http://localhost:8000/ there you can visualize an use example.
> FEAT(#152): CREATE SELECT + LABEL

- .gitignore
- SarandONGa/settings.py
- SarandONGa/urls.py
- main/templates/components/inputs.html
- main/templates/donation/list.html
- main/templates/index.html
- main/templates/master.html
- main/urls.py
- main/views.py
- static/styles/donation.css
- static/styles/master.css
Both items had using the same aesthetic as the mock up. To check it out just access the index page.
> FEAT(#97): CREATE  LABEL + INPUT COMPONENTS

- SarandONGa/urls.py
- donation/urls.py
- donation/views.py
- main/templates/donation/list.html
- main/templates/index.html
- main/templates/layouts/master.html
- main/templates/layouts/master_sidebar.html
- main/urls.py
- main/views.py
- static/styles/donation.css
- static/styles/master_sidebar.css
- I added the *extrahead* directive on master.html, so any view can add specific css files without having to load them on every view.
- When you extend the master sidebar layout into any view, you must create a specific css file for that view, and load it only in that view. You have to add the css file inside the  {% block extrahead %} directive. You can see what I made with *donation.css*. 
- I reorganised the templates directory, creating the 'layouts' folder.
- I added some styles that weren't on the mockups. Those are the hover colors. If you don't like them, just let me know and I will delete them.
- I created a custom JSON encoder so the objects array can be serialized into a JSON object. 
- I changed the colors from master sidebar layout theme. 
I'm open to suggestions 💃✨
closes …
> FEAT(#48): CREATE DONATIONS VIEW

- main/templates/subsidy_list.html
- subsidy/views.py
Certain aspects have been put in common with the listing of objects. This change is part of the homogenization of the listing.
> FIX(#119): FIX LIST SUBCENCY PROBLEMS WITH FRONTEND GROUP

- donation/models.py
Due to ASEM meeting, there was a need for adding more attribute to the model.
> FIX(#50): ADD ATTRIBUTE TO DONATION MODEL

- main/templates/components/button.html
- main/templates/index.html
- main/templates/master_sidebar.html
- static/styles/components/button.css
Added button component with different variations. The color is based on the section the button is placed, so the default button has no background color.
You can see these variations at the index view.
> FEAT(#98): CREATE BUTTON COMPONENT

- SarandONGa/urls.py
- main/templates/worker/worker_form.html
- person/forms.py
- person/views.py
Added function and form for creating a new worker
> FEAT( #28 ): ADD WORKER CREATION FORM

- donation/models.py
Now, there is a low limit for amount in donation. Yo need to donate mora than 0.1.
> FIX(#50): FIX SOME ATTRIBUTE VALIDATOR IN MODELS

- SarandONGa/urls.py
- subsidy/forms.py
- subsidy/models.py
Addition of new attributes on subsidy/models.py
> FEAT(#54): ADD NEW SUBSIDY ATTRIBUTES

- main/templates/index.html
- main/templates/layouts/master_full_width.html
@anac29 I changed some of your features (#97 and #152) because they broke when I put the container class in the layouts, so I tried to fix it. They are in a separate commit in case they need to be reversed 😄
To test this feature:
> FEAT(#93): ADD MASTER_FULL_WIDTH LAYOUT

- person/models.py
The verbose_name and the __str__ function have also been defined for the model.
Check if it complies with the established:
> FIX(#105): DELETE DUPLICATE ATTRIBUTES FROM ASEMUser MODEL 

- SarandONGa/urls.py
- donation/urls.py
- donation/views.py
- main/templates/asem_user/asem_user_form.html
- main/templates/components/card-list.html
- main/templates/components/inputs.html
- main/templates/components/navbar.html
- main/templates/godfather_form.html
- main/templates/layouts/master_sidebar.html
- main/templates/person/child/create_child.html
- main/templates/stock/list.html
- main/templates/stock/register.html
- main/templates/users/list.html
- payment/urls.py
- payment/views.py
- person/urls.py
- person/views.py
- service/urls.py
- service/views.py
- stock/forms.py
- stock/urls.py
- stock/views.py
- subsidy/urls.py
- subsidy/views.py
After merging all feature a fix was necessary to make all work.
> FIX(#188): MERGE FEATURE BACKEND + FRONTEND

- person/models.py
- person/tests.py
Tesxt case for child model. It control createe, update, delete and all exception.
> TEST(#74):CHILD CREATE TEST

- stock/tests.py
CRUD and decimal numbers for quantity tests carried out at stock/tests.py
> FEAT(#178): STOCK TESTS PERFORMED

- main/templates/components/select.html
- main/templates/layouts/master_sidebar.html
- main/templates/service/service_form.html
- main/templates/stock/register.html
- service/forms.py
- service/models.py
This is just a pull request for fixing some buttons, like "Añadir donación" button or "Añadir subvención" button, because they weren't functional. Now if you click on them, the button should work.
PS: the create service form is not finished yet. The functionality of the service form should not be reviewed.
> FIX(#146): FIX SOME BUTTONS

- donation/tests.py
Made positive and negative test for all fields creating a donation
> FEAT(#70): TEST CREATE DONATION

- person/tests_worker.py
Tests for the creation of workers implemented.
> TEST(#18): WORKER CREATION TESTS

- person/models.py
- person/tests_godfather.py
Added new tests of creation, deletion and actualization on tests_godfather.py
> TEST(#126): CREATE CREATION GODFATHER TEST

- payment/tests.py
Test for payment model, including creation, update and delete, and its only negative cases.
> TEST(#123): TEST PAYMENT CREATION

- subsidy/models.py
- subsidy/tests.py
Now the tests run with no failures
> FIX(#69): SOLVE PROBLEMS CAUSED BY MODEL UPDATE

- stock/models.py
- stock/tests.py
Seeing the tests that were in stock, the one to update was already created by a colleague before, so I have added some of the creation tests that were missing. If when reviewing one is missing, ask me for another review with those suggestions.
> TEST(#226): CREATE AND UPDATE TEST STOCK

- main/templates/subsidy_form.html
- subsidy/forms.py
- subsidy/models.py
- subsidy/urls.py
- subsidy/views.py
Added delete function for subsidies and fixed subsidy model and form for resolutions.
> FEAT(206): DELETE SUBSIDIES

- donation/forms.py
- main/templates/donation_form.html
- payment/forms.py
- person/forms.py
- person/models.py
- person/tests_child.py
- service/forms.py
- subsidy/forms.py
Fixed type of dates in forms and change some of the forms.
> FEAT(#255): FIX DATE IN FORMS

- main/templates/prueba_padrino_detalles.html
- person/urls.py
- person/views.py
Added function to get godfather details.
> FEAT(#220): GODFATHER DETAILS FUNCTION

- donation/forms.py
- main/templates/asem_user/asem_user_form.html
- main/templates/donation_form.html
- main/templates/godfather_form.html
- main/templates/payment/payment_form_malo.html
- main/templates/payment/payment_list.html
- main/templates/person/child/create_child.html
- main/templates/subsidy_form.html
- main/templates/volunteers/volunteers_form.html
- main/templates/worker/worker_form.html
- payment/forms.py
- payment/urls.py
- payment/views.py
- person/forms.py
- person/models.py
- person/tests_child.py
- service/forms.py
- subsidy/forms.py
Added function to update payments and added a test form.
> FEAT(#215): UPDATE PAYMENT

- payment/forms.py
Change input to DateTime in payment payday.
> FIX(#255): FIX DATETIME INPUT PAYMENT

- person/models.py
- person/urls.py
- person/views.py
Verbose name have also been added for the worker model.
**For the reviewe:**
Check if it complies with the established:
> FEAT(#208): ADD WORKER DELETE FUNCTION

- SarandONGa/urls.py
- main/templates/proyect/proyect_form.html
- proyect/forms.py
- proyect/models.py
- proyect/urls.py
- proyect/views.py
I have changed some things in the project model that I realized were missing, and I have also tried to cover all the errors so that they appear in the form. I have not managed to get the messages in Spanish to appear, but since a specific task is going to be created for these messages, I have left it that way for now. If you know how to modify that and you want me to change it here, please tell me. If you see anything that you see inappropriate and it is necessary to change/modify it, I say the same. To test this pr you just have to go to the project/create route and try the different attributes. I have redirected to the main page because there is no project list view.
> FEAT(#205): ADD CREATE AND PROYECT FORM

- home/forms.py
- home/models.py
- person/forms.py
- person/models.py
- person/tests_child.py
- person/tests_godfather.py
I checked that all tests pass and that you can create those entities with null termiantion date
> FIX(104): ADD START AND TERMINATION DATES TO CHILD, GODFATHER AND HOME

- main/templates/payment/payment_details.html
- payment/urls.py
- payment/views.py
Things done:
- payment_details funcion in payment/views.py
- Url added in payment/urls.py
- Template for testing the function in main/templates/payment/payment_details.html
The url for testing the function is http://localhost:8000/payment/<payment_id>
> FEAT(#276): PAYMENT DETAILS FUNCTION DONE

- stock/models.py
- stock/views.py
Before it goes well only 'cause the attribute allow null now it is fully complete
> FIX(#177): STOCK FORM NOW INCLUDE ONG

- home/models.py
- home/urls.py
- home/views.py
- main/templates/home/home_form.html
Added new url path, update method in views and changes in models.py to manage dates. Changes in create method and home_form.html.
For reviewer, you should...
- Delete all migrations
- Delete bd schemas
- Follow urls on path to get the view
> FEAT(#282): UPDATE HOME

- main/templates/components/inputs.html
- main/templates/registration/login.html
- main/views.py
- static/styles/login.css
In this pr I created the login form.
**Be sure to create a superuser first. You will have to create a NGO if none is created yet.**
You can play the next scenarios to check the form functionality:
> FEAT(#326): ADD LOGIN FORM

- home/tests.py
Creation of a positive/negative test suite for updating home model
> TEST(#316): UPDATE TEST FOR HOME

- sponsorship/tests.py
Sponsorship test fixed again due to problems during conflict resolution.
> FIX(#204): FIX SPONSORSHIP TEST AGAIN

- sponsorship/tests.py
Update test case (positive and negative) for sponsorship model
> TEST(#315): UPDATE SPONSORSHIP

- main/templates/stock/list.html
- main/templates/stock/register.html
- stock/tests.py
Testing the register form, fields + update + validation.
To check it out just run the stock tests.
> TEST(#333): TEST REGISTER VIEW FROM STOCK

- main/templates/users/list.html
- person/views.py
Pagination for ASEM Users done with default pagination of 12 objects. Changes are from line 224 to 250 plus the import; the other changes are from the formatter adding lines. Pagination for frontend template has also been added.
As you have to create at least 13 user to test this, my advice is to create the first one using the web or the admin panel, and then use MySQL Workbench to copy and paste rows so you can do it faster. First, you copy and paste the row in the person_person table, changing the ID each time. IMPORTANT to press apply after adding the rows. Then you do the same with the person_asemuser table, assigning the IDs you used before in person.
> FEAT(#429): PAGINATE ASEM USER

- person/views.py
1. - [x] Create an administrator user for one of the two NGOs.
2. - [x] Create 13 volunteers for the chosen NGO, you can do this process quickly as explained in the comments of the Pull Request #540.
3. - [x] Access the url **_/user/volunteer/list_** and check that the pagination works correctly.
> FEAT(#432): PAGINATE VOLUNTEER LIST

- main/templates/users/list.html
- person/forms.py
- person/views.py
1. - [x] Create an administrator user for one of the two NGOs.
2. - [x] Create some workers from the url **_/user/worker/create_**
3. - [x] Access the url **_/user/worker/list_** and check that the created filters work correctly.
> FEAT(#025): ADD FILTERS FOR THE LIST OF WORKERS

- SarandONGa/urls.py
- main/templates/components/card-list.html
- main/templates/donation/list.html
- main/templates/users/list.html
- person/models.py
- person/tests_asem_user.py
- person/tests_volunteer.py
Fixed also a problem with displaying null fields in the view.
The reviewer must verify that right now the Person model meets all the attributes and validations established by the team.
> FEAT(#571): REVIEW PERSON ATTRIBUTES AND VALIDATIONS

- SarandONGa/urls.py
- main/templates/donation/list.html
- person/models.py
- person/tests_worker.py
The problem with displaying null fields in the view is solved in Pull Request #582.
The reviewer must verify that right now the Worker model meets all the attributes and validations established by the team.
> FEAT(#577): REVIEW WORKER ATTRIBUTES AND VALIDATIONS

- main/templates/subsidy/list.html
- subsidy/tests.py
Using Selenium and testing both panels
Run:
Check:
> TEST(#459): ADD SUBSIDY LIST VIEW TEST

- SarandONGa/settings.py
- SarandONGa/urls.py
- main/templates/donation/list.html
- main/templates/sponsorship/sponsorship_form.html
- sponsorship/forms.py
- sponsorship/models.py
- sponsorship/tests.py
- sponsorship/views.py
I have added new validations, mostly in the form part. I couldn't think of any more, but please take your time to determine if any additional changes to the code are needed or missing. Thank you so much.
> FEAT(#573): NEW SPONSORSHIP VALIDATIONS AND SOLVE MEDIA DOCUMENT ERROR

- person/tests_asem_user_views.py
- person/views.py
Created pagination function for child list.
> FEAT(#433): CREATE PAGINATION FOR CHILD LIST

- main/templates/payment/payment_list.html
- payment/views.py
1. - [x] Create an administrator user for one of the two NGOs.
2. - [x] Create 13 payments for the chosen NGO, you can do this process quickly as explained in the comments of the Pull Request #540.
3. - [x] Access the url **_/payment/list_** and check that the pagination works correctly.
> FEAT(#431): PAGINATE PAYMENT LIST

- main/templates/stock/register.html
- stock/forms.py
- stock/models.py
- stock/tests.py
Update model, validations, forms and test
> FEAT(#565): REVISION STOCK MODEL

- SarandONGa/settings.py
- SarandONGa/urls.py
- donation/models.py
- main/templates/donation/list.html
- main/templates/person/godfather/form.html
Docs and images upload fixed. Added enctype to godfather form.
> FIX(#438): FIX IMAGES AND DOCS

- main/templates/subsidy/list.html
- subsidy/forms.py
- subsidy/views.py
Created subsidy filter form and view
> FEAT(#480): SUBSIDY FILTER

- main/templates/payment/payment_list.html
- payment/forms.py
- payment/views.py
Created payment filter form and view
> FEAT(#479): PAYMENT FILTER

- main/templates/subsidy/create.html
- main/templates/subsidy/list.html
- subsidy/forms.py
- subsidy/models.py
- subsidy/tests.py
Changes in subsidy model in order to follow new Conceptual model changes
> FEAT(#563): NEW SUBSIDY ATTRIBUTES

- .vscode/settings.json
- main/templates/payment/payment_form.html
- payment/test_view.py
- payment/urls.py
- payment/views.py
Only Payment view is tested.
You can find these in "payment/tests_view.py"
> TEST(#460): PAYMENT FORM VIEW TESTS

- main/templates/project/list.html
- main/templates/stock/list.html
- stock/forms.py
- stock/views.py
Function to filter and search a product done. Provisional frontend added. To review it:
> FEAT(#427): FILTER STOCK PRODUCTS

- donation/models.py
- donation/tests.py
Revised donation attributes making some of these required and making dni validator.
> FEAT(#561): REVISE DONATION ENTITY

- person/forms.py
- person/views.py
The CharField type attributes have been grouped into a single search engine.
1. - [ ] Create an administrator user for one of the two NGOs.
2. - [ ] Create some workers from the url **_/user/worker/create_**
3. - [ ] Access the url **_/user/worker/list_** and check that the created filters work correctly.
> FIX(#025): FIX FILTERS FOR THE LIST OF WORKERS

- donation/forms.py
- donation/views.py
- main/templates/donation/list.html
Creation of filter donation form to search a specific donation
> FEAT(#46): CREATE DONATION FILTER FORM

- service/tests.py
Positive and negative test case for updating a service
> TEST(#317): TEST CASE FOR UPDATING SERVICE

- SarandONGa/settings.py
- service/models.py
> FEAT(#568): SERVICE AMOUNT REVIEWED

- main/templates/users/list.html
- person/forms.py
- person/views.py
1. - [x] Create an administrator user for one of the two NGOs.
2. - [x] Create 13 volunteers for the chosen NGO, you can do this process quickly as explained in the comments of the Pull Request #540.
3. - [x] Access the url **_/user/volunteer/list_** and check that the pagination works correctly, keeping the filters when used.
> FIX(#432): KEEP VOLUNTEER FILTERS WITH PAGINATION

- main/templates/components/card-list.html
With this pr mobile buttons should be working
> FIX(#334): FIX MOBILE BUTTONS LINKS

- person/models.py
- person/tests_child.py
I made secondary atributes of child (such as father's name, father's profession and so) nullable, because VidesSur never told us to make them mandatory
> FEAT(#572): CHANGE NULLABLE OF SOME CHILD'S ATRIBUTES

- person/models.py
The reviewer must verify that right now the zip code in Person and Worker models meets all the criteria and validations established by the team.
The reviewer must verify that right now the Person model meets all the attributes and validations established by the team.
To find out how the validator has been formed, you can obtain more information about the postal codes of the different countries by clicking [here](https://www.azcodigopostal.com/).
> FIX(#571): FIX ZIP CODE VALIDATOR

- main/templates/components/navbar.html
- main/templates/update_password.html
- static/styles/login.css
With this pr you could update your password.
For reviewing this PR you can:
> FEAT(#472): ADD UPDATE PASSWORD VIEW

- main/templates/index.html
- static/styles/index.css
Pricing view created. Just run the app and in the index view for not logged users, at the end of the page there is a table with adetailed pricing. The button to access to the paying gateway works, however the gateway is not available in ths branch.
> FEAT(#663): CREATE PRICING VIEW

- main/templates/payment/payment_form.html
- payment/forms.py
- payment/models.py
- payment/views.py
Added blank true to relations so they are not required in form by default.
Fix create payment so you don't have to be a godfather to create one.
> FIX(#567): FIX PAYMENT MODEL AND VIEWS

- main/templates/asem_user/asem_user_form.html
- main/templates/components/button.html
- main/templates/components/navbar.html
- main/templates/layouts/master_sidebar.html
- main/templates/stock/register.html
- main/templates/users/details.html
- person/views.py
- static/styles/master_sidebar.css
- static/styles/users.css
Fix buttons + urls.
I have corrected al buttons that seemed a bit weid, the urls for example when you go to details now yu can click on 'volver al listado' without crashing, I have also corrected some backend errors, added margins, and corrected the 'apayo finaciero' section from the navbar.
Just navigate through the pages to check if you notice something weird in realation with what I have corrected.
> FIX(#652): FIX BUTTONS

- main/templates/index.html
- main/templates/index/index-asem.html
- main/templates/index/index-videssur.html
The pricing tables needed to be in all indexes.
To check it out access to all the home pages, logged and not logged ones.
> FIX(#663):  FIX PRICING TABLES

- service/models.py
Added validator to check the relationship between payment and service
> FEAT(#566): CHECK SERVICE MODEL

- main/templates/person/workers/register.html
- main/templates/registration/login.html
> FEAT(#687): ADD PRIVACY POLICY FIELDS

- main/templates/canceled.html
Changes on href in canceled template
> FIX(#560): FIX GATEWAY CANCEL PROCESS

- person/models.py
> FIX(#653): FIX VOLUNTEER MODEL

- main/templates/layouts/master_sidebar.html
- main/templates/stock/list.html
- person/models.py
- person/views.py
Integrity error raised by unique together fixed. Check that it doesn't let you create 2 volunteers with the same DNI and that the error appears in the form. Check also that you can download asem users, children, godfathers and volunteers and that the Download button doesn't appear in the other entities.
> FIX(develop): FIX UNIQUE TOGETHER ERROR

- main/templates/person/users/list.html
There were quotation marks missing
> FIX(#27): FIX USER PHOTO LINK

- main/templates/project/list.html
- requirements.txt
Added script to keep the query if you delete a project.
To review:
> FIX(#729): FIX DELETE PROJECT LINK

- main/templates/project/list.html
- requirements.txt
Added urllib3 to requirements.txt.
> FIX(#729): FIX ACTIONS

- main/templates/index/index-videssur.html
To review, just check in index-videssur.html that the name of the image is the same as in the static folder.
> FIX(#721): FIX VIDESSUR LOGO IMG

- main/templates/components/card-list.html
- main/templates/person/users/list.html
Added script to keep the query if you delete a person.
To review:
> FIX(#725): FIX DELETE PERSON LINK

- main/templates/project/list.html
Fixed delete link in mobile devices.
> FIX(#733): FIX DELETE PROJECT LINK MOBILES

- main/templates/sponsorship/sponsorship_form.html
To review this, you can access with VidesSur credentials and go to some child or godfather / home in order to create a new sponsorship.
You should be able to see a message below multiple selects.
> FIX(#741): SHOW INFO ON MULTIPLE SELECT INPUTS

- payment/test_view.py
- payment/views.py
- service/forms.py
- service/views.py
You have to check it for the project and for the godfather.
Access the "Añadir pago" view of the entity, add a payment, and verify that the entity is maintained both in the form and in the URL. Also access the payment view and check that adding one does not maintain any project.
Also try the same adding a service to a ASEM User. I have also filtered payments to only show ASEM payments. Before it was showing an error.
Also I have added the exploratory test. You can check it by running "python manage.py test payment.test_view".
> FIX(#734): PAYMENT FORM NOT MANTAINING SUBJECT

- person/views.py
The initial task was to check if filters work as AND or OR filters. They work as intended as AND. While checking this I found that in volunteer details there were fields that were not displayed so I fixed that.
To review, check that all boolean fields show in volunteer details and asem user details.
> FIX(#723): FIX FILTERS

- main/load_test.py
In this PR I created a locust file to set up the load test. I did it on the deploy, so you shouldn't execute them unless you are sure you want to do it.
You can check results I got here:
[load_test_report.pdf](https://github.com/ISPP-12/SarandONGa/files/11430563/load_test_report.pdf)
I only set up for getting the home page and then login with VidesSur credentials, because I didn't want to break things on deploy. However, there are many failures as you can see, so it is really certain.
> TEST(#745): ADD LOAD TEST WITH LOCUST
